### ISSUE TITLE
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("rdbs8_conv2/Relu:0",...) at layer "concatenate_42")

### ISSUE THREAD

**Issue by karsil** [anish9/Deblur-Network#1]
When executing the `inference` file, I'll recieve the following error:
```python
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("rdbs8_conv2/Relu:0", shape=(?, ?, ?, 32), dtype=float32) at layer "concatenate_42". The following previous layers were accessed without issue: ['input_1', 'convg_1', 'batch_normalization', 'activation', 'convg_2', 'batch_normalization_2', 'activation_2', 'rdbs8_conv1', 'rdbs7_conv1', 'rdbs6_conv1', 'rdbs5_conv1', 'rdbs4_conv1', 'rdbs3_conv1', 'rdbs2_conv1', 'rdbs1_conv1']
```

I tried to debug the problem to find a possible broken concatenation and found out, that the specific tensor is being added in `layers.py` in the `RDBlocks` function when executing:
```python
pas = Convolution2D(filters=g, kernel_size=(3,3), strides=(1, 1), padding='same' , activation='relu', name = name+'_conv'+str(i))(out)
```
Sadly, I didn't found the broken concatenation...

**Versions:**
- TensorFlow: 1.15.0

Happy for any hints/solutions, interesting project!

**Comment by anish9** [comment]
@karsil  may I know what version of tensor flow are you using??

**Comment by karsil** [comment]
> @karsil may I know what version of tensor flow are you using??

Sure, TF is 1.15.0 (edited 1st post)

**Comment by anish9** [comment]
@karsil  can you try with tf1.12

**Comment by karsil** [comment]
I've installed tf 1.12 via `conda install tensorflow=1.12` and got a new error regarding `tensorflow-estimator`. I needed to additionally install `conda install tensorflow-estimator=1.13` (oldest available version for conda), from which on I was able to run the project! (Still needed to fix the model path in the `inference` file though)
